language: node_js

sudo: required

node_js:
  - "9.11.2"

env:
  - TEST_SUITE=QUICK_TESTING
  - TEST_SUITE=MEDIUM_TESTING
  - TEST_SUITE=FULL_TESTING

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - npm install -g npm@latest
  - npm install -g ganache-cli truffle

install:
  - npm install 

script:
  - TESTING_MODE=$TEST_SUITE LOG_GAS=true npm run test